name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build && ls -la ./dist/

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: 164.92.168.227
        username: root
        key: ${{ secrets.DO_API_KEY }}
        source: ./dist/
        target: /home/tornado-blog-app/tornado-blog-app-be/dist
        overwrite: true

    - name: Restart app
      uses: appleboy/ssh-action@master
      with:
        host: 164.92.168.227
        username: root
        key: ${{ secrets.DO_API_KEY }}
        script: |
          pm2 restart tornado-blog-app
