name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
        
    - name: Verify contents of dist folder
      run: ls -la ./dist/
        
    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.DO_MY_APPS_HOST }}
       username: ${{ secrets.DO_MY_APPS_USERNAME }}
       key: ${{ secrets.DO_SSH_KEY }}
       source: ./dist/
       target: /home/tornado-blog-app/tornado-blog-app-be/
       overwrite: true

    - name: Restart app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_MY_APPS_HOST }}
        username: ${{ secrets.DO_MY_APPS_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          pm2 restart tornado-blog-app || exit 1
